services:
  - type: web
    name: mediconnect-backend
    env: java
    buildCommand: "./mvnw clean install -DskipTests"
    startCommand: "java -jar target/app.jar"
    envVars:
      - key: SPRING_DATASOURCE_URL
        sync: false
      - key: SPRING_DATASOURCE_USERNAME
        sync: false
      - key: SPRING_DATASOURCE_PASSWORD
        sync: false
      - key: SPRING_JPA_HIBERNATE_DDL_AUTO
        value: update
